name: Terraform Validate

on:
  push:
    paths:
      - 'monitoring-stack/**.tf'
      - 'monitoring-stack/**.tfvars'
      - '.github/workflows/terraform-validate.yml'
  pull_request:
    paths:
      - 'monitoring-stack/**.tf'
      - 'monitoring-stack/**.tfvars'
      - '.github/workflows/terraform-validate.yml'

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: monitoring-stack
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate
