name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - 'monitoring-stack/**.tf'
      - 'monitoring-stack/**.tfvars'
      - '.github/workflows/terraform-ci.yml'
  pull_request:
    paths:
      - 'monitoring-stack/**.tf'
      - 'monitoring-stack/**.tfvars'
      - '.github/workflows/terraform-ci.yml'
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: monitoring-stack
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        continue-on-error: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
        continue-on-error: false

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
        continue-on-error: false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: false

      - name: Terraform Init
        run: terraform init
        continue-on-error: false

      - name: Terraform Validate
        run: terraform validate
        continue-on-error: false

      - name: Terraform Plan
        run: terraform plan -no-color
        continue-on-error: false

  terraform-apply:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: terraform-plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: monitoring-stack
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        continue-on-error: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
        continue-on-error: false

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
        continue-on-error: false

      - name: Terraform Init
        run: terraform init
        continue-on-error: false

      - name: Terraform Apply
        run: terraform apply -auto-approve
        continue-on-error: false